---
# Anything specified in the retired_files variable will be deleted.
# This is uncommented as I had issues with everything being deleted when this was just present as an empty key.
# May be something to investigate.
retired_files:
  - .readme/static/borrowed/sdp_overview.png
  - .github/workflows/build.yml
